[versions]
agp = "9.0.0"
kotlin = "2.3.0"
compose-multiplatform = "1.10.0"
androidx-activity-compose = "1.9.2"
exifinterface = "1.3.7"
lifecycle = "2.10.0-alpha06"
accompanist = "0.34.0"
camerax = "1.5.1"
coroutines = "1.10.2"
paging-common = "3.3.0-alpha02-0.5.1"
paging-compose-common = "3.3.0-alpha02-0.4.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "coroutines" }
paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging-common" }
paging-compose-common = { module = "app.cash.paging:paging-compose-common", version.ref = "paging-compose-common" }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose-multiplatform" }

[plugins]
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
